CC = g++
CFLAGS = -Wall -g
# DEPS=le_commonListFunction.h

le_mergeTwoSortedList:le_mergeTwoSortedList.o le_commonListFunction.o
	$(CC) $(CFLAGS) -o le_mergeTwoSortedList le_mergeTwoSortedList.o le_commonListFunction.o

le_commonListFunction.o: le_commonListFunction.h
